<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sujan Bhattarai">

<title>Applied Statistics for Social Sciences: How incentivizing household failed?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../pic.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../../featured_style_projects.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../featured_projects.html" rel="" target="">
 <span class="menu-text">DS-projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html" rel="" target="">
 <span class="menu-text">Analytics-projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../certifications.html" rel="" target="">
 <span class="menu-text">Certificates</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1-treatment-ignorability-assumption-and-applying-matching-estimators" id="toc-part-1-treatment-ignorability-assumption-and-applying-matching-estimators" class="nav-link active" data-scroll-target="#part-1-treatment-ignorability-assumption-and-applying-matching-estimators">Part 1 Treatment Ignorability Assumption and Applying Matching Estimators</a></li>
  <li><a href="#part-2-panel-model-and-fixed-effects" id="toc-part-2-panel-model-and-fixed-effects" class="nav-link" data-scroll-target="#part-2-panel-model-and-fixed-effects">Part 2 Panel model and fixed effects</a></li>
  <li><a href="#first-difference-and-fixed-effects-and-omitted-variable-problems" id="toc-first-difference-and-fixed-effects-and-omitted-variable-problems" class="nav-link" data-scroll-target="#first-difference-and-fixed-effects-and-omitted-variable-problems">First Difference and Fixed Effects and Omitted Variable Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Applied Statistics for Social Sciences: How incentivizing household failed?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Statistics</div>
    <div class="quarto-category">Econometrics</div>
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sujan Bhattarai </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>The goal is to estimate the causal effect of maternal smoking during pregnancy on infant birth weight using the treatment ignorability assumptions. The data are taken from the National Natality Detail Files, and the extract “SMOKING_EDS241.csv”’ is a random sample of all births in Pennsylvania during 1989-1991. Each observation is a mother-infant pair. The key variables are:</p>
<p><strong>The outcome and treatment variables are:</strong></p>
<p>birthwgt=birth weight of infant in grams</p>
<p>tobacco=indicator for maternal smoking</p>
<p><strong>The control variables are:</strong></p>
<p>mage (mother’s age), meduc (mother’s education), mblack (=1 if mother identifies as Black), alcohol (=1 if consumed alcohol during pregnancy), first (=1 if first child), diabete (=1 if mother diabetic), anemia (=1 if mother anemic)</p>
<section id="part-1-treatment-ignorability-assumption-and-applying-matching-estimators" class="level3">
<h3 class="anchored" data-anchor-id="part-1-treatment-ignorability-assumption-and-applying-matching-estimators">Part 1 Treatment Ignorability Assumption and Applying Matching Estimators</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data for Part </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>smoking_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"featured_projects/econometrics/data/SMOKING_EDS241.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="mean-differences-assumptions-and-covariates" class="level4">
<h4 class="anchored" data-anchor-id="mean-differences-assumptions-and-covariates">Mean Differences, Assumptions, and Covariates</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate mean difference. Remember to calculate a measure of statistical significance</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="do">## calculating difference using t.test when tobacco is 1 and 0</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>smoking_mothers <span class="ot">=</span> smoking_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(tobacco <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>non_smoking_mothers <span class="ot">=</span> smoking_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(tobacco <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#peform t-test to see if the difference is significant in other covariates</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(smoking_mothers<span class="sc">$</span>birthwgt, non_smoking_mothers<span class="sc">$</span>birthwgt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  smoking_mothers$birthwgt and non_smoking_mothers$birthwgt
t = -58.932, df = 26945, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -252.6727 -236.4060
sample estimates:
mean of x mean of y 
 3185.747  3430.286 </code></pre>
</div>
</div>
<p>The mean difference is 244.539 grams between child from smoker and non smoker mothers, which is significant at 5% confidence.The assumptions for this mean difference to hold is ignorability (no other confounding variables that is influencing the outcome) and common support( there is sufficient overlap between treatment and control group. I mean the units in both treatment and control group are similar which means units being compared is similar.</p>
<p><strong>Creating sets of coefficents to explain the weights of each covariates for this outcome</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set options to have maximum 5 decimal</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits=</span><span class="dv">5</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="do">## For continuous variables you can use the t-test</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test()</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>education <span class="ot">&lt;-</span> <span class="fu">t.test</span>(smoking_mothers<span class="sc">$</span>meduc, non_smoking_mothers<span class="sc">$</span>meduc)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">t.test</span>(smoking_mothers<span class="sc">$</span>mage, non_smoking_mothers<span class="sc">$</span>mage)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>birthwht <span class="ot">&lt;-</span> <span class="fu">t.test</span>(smoking_mothers<span class="sc">$</span>birthwgt, non_smoking_mothers<span class="sc">$</span>birthwgt)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="do">## For binary variables you should use the proportions test</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#prop.test()</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>alcohol <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="fu">table</span>(smoking_mothers<span class="sc">$</span>alcohol), <span class="fu">table</span>(non_smoking_mothers<span class="sc">$</span>alcohol))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>first_child <span class="ot">&lt;-</span><span class="fu">prop.test</span>(<span class="fu">table</span>(smoking_mothers<span class="sc">$</span>first), <span class="fu">table</span>(non_smoking_mothers<span class="sc">$</span>first))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>diabetes<span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="fu">table</span>(smoking_mothers<span class="sc">$</span>diabete), <span class="fu">table</span>(non_smoking_mothers<span class="sc">$</span>diabete))</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>anaemia <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="fu">table</span>(smoking_mothers<span class="sc">$</span>anemia),  <span class="fu">table</span>(non_smoking_mothers<span class="sc">$</span>anemia))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>black   <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="fu">table</span>(smoking_mothers<span class="sc">$</span>mblack),  <span class="fu">table</span>(non_smoking_mothers<span class="sc">$</span>mblack))</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Covariate Calculations and Tables (feel free to use code from Assignment 1 key)</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># create dataframe of coefficents from above results including</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="co"># first column should be variable name, then mean of estimate for sample 1, then</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># mean of sample 2, then p values </span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"birthweight"</span>, <span class="st">"education"</span>, <span class="st">"age"</span>, <span class="st">"alcohol"</span>, <span class="st">"first_child"</span>, <span class="st">"diabetes"</span>, <span class="st">"anaemia"</span>, <span class="st">"black"</span>),</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoking_mothers =</span> <span class="fu">c</span>(birthwht<span class="sc">$</span>estimate[<span class="dv">1</span>], education<span class="sc">$</span>estimate[<span class="dv">1</span>], age<span class="sc">$</span>estimate[<span class="dv">1</span>], </span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">sum</span>(smoking_mothers<span class="sc">$</span>alcohol)<span class="sc">/</span><span class="fu">length</span>(smoking_mothers<span class="sc">$</span>alcohol),  </span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">sum</span>(smoking_mothers<span class="sc">$</span>first)<span class="sc">/</span><span class="fu">length</span>(smoking_mothers<span class="sc">$</span>first), </span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">sum</span>(smoking_mothers<span class="sc">$</span>diabete)<span class="sc">/</span><span class="fu">length</span>(smoking_mothers<span class="sc">$</span>diabete), </span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">sum</span>(smoking_mothers<span class="sc">$</span>anemia)<span class="sc">/</span><span class="fu">length</span>(smoking_mothers<span class="sc">$</span>anemia), </span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">sum</span>(smoking_mothers<span class="sc">$</span>mblack)<span class="sc">/</span><span class="fu">length</span>(smoking_mothers<span class="sc">$</span>mblack)),</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">non_smoking_mothers =</span> <span class="fu">c</span>(birthwht<span class="sc">$</span>estimate[<span class="dv">2</span>], education<span class="sc">$</span>estimate[<span class="dv">2</span>], age<span class="sc">$</span>estimate[<span class="dv">2</span>], </span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">sum</span>(non_smoking_mothers<span class="sc">$</span>alcohol)<span class="sc">/</span><span class="fu">length</span>(non_smoking_mothers<span class="sc">$</span>alcohol),</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">sum</span>(non_smoking_mothers<span class="sc">$</span>first)<span class="sc">/</span><span class="fu">length</span>(non_smoking_mothers<span class="sc">$</span>first),</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">sum</span>(non_smoking_mothers<span class="sc">$</span>diabete)<span class="sc">/</span><span class="fu">length</span>(non_smoking_mothers<span class="sc">$</span>diabete), </span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">sum</span>(non_smoking_mothers<span class="sc">$</span>anemia)<span class="sc">/</span><span class="fu">length</span>(non_smoking_mothers<span class="sc">$</span>anemia), </span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">sum</span>(non_smoking_mothers<span class="sc">$</span>mblack)<span class="sc">/</span><span class="fu">length</span>(non_smoking_mothers<span class="sc">$</span>mblack)),</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="fu">round</span>(<span class="fu">c</span>(birthwht<span class="sc">$</span>p.value, </span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>                    education<span class="sc">$</span>p.value, </span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>                    age<span class="sc">$</span>p.value, </span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>                    alcohol<span class="sc">$</span>p.value, </span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>                    first_child<span class="sc">$</span>p.value, </span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>                    diabetes<span class="sc">$</span>p.value, </span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>                    anaemia<span class="sc">$</span>p.value, </span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>                    black<span class="sc">$</span>p.value), <span class="dv">6</span>))</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     variable smoking_mothers non_smoking_mothers p_value
1 birthweight      3.1857e+03          3.4303e+03       0
2   education      1.1921e+01          1.3239e+01       0
3         age      2.5539e+01          2.7453e+01       0
4     alcohol      4.4182e-02          7.1033e-03       0
5 first_child      3.6459e-01          4.3609e-01       0
6    diabetes      1.7519e-02          1.7364e-02       0
7     anaemia      1.4103e-02          7.8005e-03       0
8       black      1.3541e-01          1.0863e-01       0</code></pre>
</div>
</div>
<p>For all other covariates, there is significant difference between the treatment and control groups under 5% confidence interval. The p value is extremely low that it rounds to zero even at rounding at 6 decimal places. This suggests that the assumptions, Common Support, is not satisfied. There isn’t sufficient overlap between treatment and control group, which means smoking mothers and non smoking mothers already represent disimilar population. Regardding ignorability assumption, we cannot yet make inference from t-test. The part b, where ATE will be used, will help us test the ignorability assumption.</p>
</section>
<section id="ate-and-covariate-balance" class="level4">
<h4 class="anchored" data-anchor-id="ate-and-covariate-balance">ATE and Covariate Balance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ATE Regression univariate</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tobacco_univariate <span class="ot">&lt;-</span> <span class="fu">lm</span>(birthwgt <span class="sc">~</span> tobacco, <span class="at">data =</span> smoking_data)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ATE with covariates</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>tobacco_covariates <span class="ot">&lt;-</span> <span class="fu">lm</span>(birthwgt <span class="sc">~</span>  tobacco <span class="sc">+</span> mage <span class="sc">+</span>  meduc <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                           mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia, <span class="at">data =</span> smoking_data)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="do">## create combined table</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(tobacco_univariate, tobacco_covariates, <span class="at">type =</span> <span class="st">"text"</span>, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">out.header =</span> <span class="cn">TRUE</span>, </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Regression with and without controls"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">notes.label =</span> <span class="st">"significance level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression with and without controls
===========================================================================
                                      Dependent variable:                  
                    -------------------------------------------------------
                                           birthwgt                        
                                (1)                         (2)            
---------------------------------------------------------------------------
tobacco                     -244.540***                 -228.070***        
                              (4.079)                     (4.177)          
                                                                           
mage                                                      -0.694*          
                                                          (0.357)          
                                                                           
meduc                                                    11.688***         
                                                          (0.860)          
                                                                           
mblack                                                  -240.030***        
                                                          (5.106)          
                                                                           
alcohol                                                  -77.350***        
                                                          (13.465)         
                                                                           
first                                                    -96.944***        
                                                          (3.447)          
                                                                           
diabete                                                  73.228***         
                                                          (12.104)         
                                                                           
anemia                                                     -4.796          
                                                          (16.754)         
                                                                           
Constant                    3,430.300***                3,362.300***       
                              (1.791)                     (11.927)         
                                                                           
---------------------------------------------------------------------------
Observations                   94,173                      94,173          
R2                             0.037                       0.072           
Adjusted R2                    0.037                       0.072           
Residual Std. Error     493.750 (df = 94171)        484.730 (df = 94164)   
F Statistic         3,594.300*** (df = 1; 94171) 909.180*** (df = 8; 94164)
===========================================================================
significance level                              *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Based on the regression output, the base weight of child born from control population(non smoking mothers) is 3430.300 gram on average. But, for the treatment population who are smoking mothers, the base weight of child born from them has lower weight by 244 grams on average. In other words, there is an average lower weight of child born from smoking mothers. This finding is statistically significant as evident by p values, which is much less than 0.05. However, only 3% of variation in birthweight is explained by the model, given by R squared value of 0.03.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform balance test</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">xBalance</span>(tobacco <span class="sc">~</span> mage <span class="sc">+</span>  meduc <span class="sc">+</span> mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia <span class="sc">+</span> birthwgt,  <span class="at">data =</span> smoking_data,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">report=</span><span class="fu">c</span>(<span class="st">"std.diffs"</span>,<span class="st">"chisquare.test"</span>, <span class="st">"p.values"</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#use staragazer to present the results</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(x[<span class="dv">1</span>]) <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>   <span class="co">#round last column to 5 digit</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#rename columns based on number index</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setNames</span>(<span class="fu">c</span>( <span class="st">"chi-Square/standard difference test"</span>, <span class="st">"p-value"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         chi-Square/standard difference test p-value
mage                                -0.36194  0.0000
meduc                               -0.64374  0.0000
mblack                               0.08439  0.0000
alcohol                              0.31525  0.0000
first                               -0.14500  0.0000
diabete                              0.00119  0.8858
anemia                               0.06670  0.0000
birthwgt                            -0.49527  0.0000</code></pre>
</div>
</div>
<p>Based on the outputs above, several covariates, except the presence of diabetes in mothers, shows statistically significant relationships with birthweight, having p values close to zero. This means our assumption of ignorability for this observational studies is violated and not fulfilled becuase there are several confounders that is significantly influencing the outcome. So we can’t make casual inference that tobacco has caused lower birth weights in smoker mothers.</p>
</section>
<section id="propensity-score-estimation" class="level4">
<h4 class="anchored" data-anchor-id="propensity-score-estimation">Propensity Score Estimation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Propensity Scores estimation with logistic regression</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mother_prospensityscore <span class="ot">&lt;-</span> <span class="fu">glm</span>(tobacco <span class="sc">~</span>  mage <span class="sc">+</span>  meduc <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                           mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia <span class="sc">+</span> birthwgt, <span class="at">data =</span> smoking_data,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="do">## create a table of coefficients</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>stargazer<span class="sc">::</span> <span class="fu">stargazer</span>(mother_prospensityscore, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=============================================
                      Dependent variable:    
                  ---------------------------
                            tobacco          
---------------------------------------------
mage                       -0.040***         
                            (0.002)          
                                             
meduc                      -0.288***         
                            (0.005)          
                                             
mblack                     -0.361***         
                            (0.028)          
                                             
alcohol                    1.962***          
                            (0.062)          
                                             
first                      -0.460***         
                            (0.020)          
                                             
diabete                    0.229***          
                            (0.067)          
                                             
anemia                     0.333***          
                            (0.081)          
                                             
birthwgt                   -0.001***         
                           (0.00002)         
                                             
Constant                   6.456***          
                            (0.090)          
                                             
---------------------------------------------
Observations                94,173           
Log Likelihood            -40,841.000        
Akaike Inf. Crit.         81,699.000         
=============================================
Note:             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create regression table dataframe based on mother_prospensityscore</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a regression model object named 'model'</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># You would need to replace 'model' with the actual name of your model object</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> mother_prospensityscore</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients, standard errors, and p-values from the model</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>coefficients <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>standard_errors <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(model)))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>p_values <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients[, <span class="dv">4</span>]  <span class="co"># Extracting p-values</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to determine significance level</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>get_significance_level <span class="ot">&lt;-</span> <span class="cf">function</span>(p_value) {</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (p_value <span class="sc">&lt;</span> <span class="fl">0.01</span>) {</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">'***'</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">'**'</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (p_value <span class="sc">&lt;</span> <span class="fl">0.1</span>) {</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">'*'</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">''</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Get significance levels</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>significance_levels <span class="ot">&lt;-</span> <span class="fu">sapply</span>(p_values, get_significance_level)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dataframe</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">Coefficient =</span> coefficients,</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">Standard_error =</span> <span class="fu">round</span>(standard_errors, <span class="dv">3</span>),</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">Significance_level =</span> significance_levels</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the dataframe</span></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Coefficient Standard_error Significance_level
(Intercept)  6.45614093          0.090                ***
mage        -0.04012754          0.002                ***
meduc       -0.28772570          0.005                ***
mblack      -0.36100043          0.028                ***
alcohol      1.96216177          0.062                ***
first       -0.45972476          0.020                ***
diabete      0.22927944          0.067                ***
anemia       0.33284394          0.081                ***
birthwgt    -0.00091614          0.000                ***</code></pre>
</div>
</div>
<p>The covariates coefficients are strengths/weights of each variables that determines whether a unit will recieve the treatment. For example, the coefficient of mother’s age is 0.04, which means that for every unit increase in mother’s age, keeping all other covariates constant, the log odds of being in treatment group decreases by 0.02.This is statistically significant as evident by p value, which is much less than 0.05. All covariates in the model are significant which means they are all important in determining the treatment status for a unit X.</p>
<p>Among all covariates, alchol has the greatest influence on whether a unit will recieve treatment, followed by first born child, which negative influence in being treatment group. These coefficients are all significant at 5% significance level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## use this logistic model to create a new column of prospensity scores for each observation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>smoking_data<span class="sc">$</span>prospensity_scores <span class="ot">&lt;-</span> <span class="fu">predict</span>(mother_prospensityscore, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#round the scores to 2 decimal places</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>smoking_data<span class="sc">$</span>prospensity_scores <span class="ot">&lt;-</span> <span class="fu">round</span>(smoking_data<span class="sc">$</span>prospensity_scores, <span class="dv">2</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Histogram of PS before matching</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">histbackback</span>(<span class="fu">split</span>(smoking_data<span class="sc">$</span>prospensity_scores, smoking_data<span class="sc">$</span>tobacco),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">main=</span> <span class="st">"Propensity score before matching"</span>,  </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">xlab=</span><span class="fu">c</span>(<span class="st">"control"</span>,  <span class="st">"treatment"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Overlap and its meaning</strong> Overlap refers to the degree of similarity or commonality between the treatment group (those who received the treatment being studied) and the control group (those who did not receive the treatment). The overlap is important because it is a necessary condition for the ignorability assumption to hold. If there is no overlap, then the treatment and control groups are so different that it is impossible to make causal inferences. The histogram above shows that there is a only some overlap between the treatment and control group, more individuals in the control group with lower propensity scores than in the treatment group. This is a violation of the Common Support assumption.</p>
</section>
<section id="matching-balance" class="level4">
<h4 class="anchored" data-anchor-id="matching-balance">Matching Balance</h4>
<p>Next, match treated/control mothers using your estimated propensity scores and nearest neighbor matching. Compare the balancing of pretreatment characteristics (covariates) between treated and non-treated units in the original dataset (from c) with the matched dataset (think about comparing histograms/regressions).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Nearest-neighbor Matching</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>prospensity_score_matched <span class="ot">&lt;-</span> MatchIt<span class="sc">::</span><span class="fu">matchit</span>(tobacco <span class="sc">~</span>  mage <span class="sc">+</span>  meduc <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                             mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia <span class="sc">+</span> birthwgt, <span class="at">data =</span> smoking_data, <span class="at">method =</span> <span class="st">"nearest"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Covariate Imbalance post matching</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>matched_prospensity_dataset <span class="ot">&lt;-</span> <span class="fu">match.data</span>(prospensity_score_matched)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Drawing back to back histograms for propensity scores for treated and </span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># non-treated after matching</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">histbackback</span>(<span class="fu">split</span>(matched_prospensity_dataset<span class="sc">$</span>prospensity_scores,  matched_prospensity_dataset<span class="sc">$</span>tobacco),   <span class="at">main=</span> <span class="st">"Propensity</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="st">        score   after   matching"</span>,  <span class="at">xlab=</span><span class="fu">c</span>(<span class="st">"control"</span>,   <span class="st">"treatment"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Post matching, there is a better overlap between the treatment and control group. Units with high propensity score is matched with its counterparts and vice versa. This means the units we are comparing between the treatment and control group are similar. This helps us define counterfactuals of what would have happened to the treatment group if they were not treated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the covariates between treated and non-treated that were used in the</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># estimation of the propensity scores</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">xBalance</span>(tobacco <span class="sc">~</span> mage <span class="sc">+</span>  meduc <span class="sc">+</span> mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia <span class="sc">+</span> birthwgt, <span class="at">data =</span> matched_prospensity_dataset,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">report=</span><span class="fu">c</span>(<span class="st">"std.diffs"</span>,<span class="st">"chisquare.test"</span>, <span class="st">"p.values"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         strata():  unstrat    
         stat      std.diff    
vars                           
mage                    0.0 ***
meduc                   0.0 ***
mblack                  0.0 ** 
alcohol                 0.1 ***
first                   0.0 ***
diabete                 0.0 .  
anemia                  0.0    
birthwgt                0.0 *  
---Overall Test---
        chisquare df p.value
unstrat       175  8   1e-33
---
Signif. codes:  0 '***' 0.001 '** ' 0.01 '*  ' 0.05 '.  ' 0.1 '   ' 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xBalance</span>(tobacco <span class="sc">~</span> mage <span class="sc">+</span>  meduc <span class="sc">+</span> mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia <span class="sc">+</span> birthwgt, <span class="at">data =</span> smoking_data,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">report=</span><span class="fu">c</span>(<span class="st">"std.diffs"</span>,<span class="st">"chisquare.test"</span>, <span class="st">"p.values"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         strata():  unstrat     
         stat      std.diff     
vars                            
mage                   -0.4 *** 
meduc                  -0.6 *** 
mblack                  0.1 *** 
alcohol                 0.3 *** 
first                  -0.1 *** 
diabete                 0.0     
anemia                  0.1 *** 
birthwgt               -0.5 *** 
---Overall Test---
        chisquare df p.value
unstrat     10298  8       0
---
Signif. codes:  0 '***' 0.001 '** ' 0.01 '*  ' 0.05 '.  ' 0.1 '   ' 1 </code></pre>
</div>
</div>
<p>After the matching, the nature and weight of the regression coefficients changed. Previously in unmatched data, I discussed that with increase age of mother, propensity score decreases. But post matching, the coefficients is showing that propensity score actually increases with increasing age of the mother. This is a sign that matching have accounted fixed effects in the observational dataset. Moreover, some covariates which were significant in determining the treatement status in the pre matching, are not significant anymore post matching. Like diabete, anemia, birthwgt, and mblack. Thus mother being black, having diabetes, and having anaemia, does not determine if she will receive the treatment or not.</p>
</section>
<section id="ate-with-nearest-neighbor" class="level4">
<h4 class="anchored" data-anchor-id="ate-with-nearest-neighbor">ATE with Nearest Neighbor</h4>
<p>Estimate the ATT using the matched dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate ATE based on nearest neighbor matching</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sumdiff_data <span class="ot">&lt;-</span> matched_prospensity_dataset<span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subclass)<span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> birthwgt[tobacco<span class="sc">==</span><span class="dv">1</span>]<span class="sc">-</span> birthwgt[tobacco<span class="sc">==</span><span class="dv">0</span>])</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>dif_in_treated <span class="ot">&lt;-</span> <span class="fu">sum</span>(sumdiff_data<span class="sc">$</span>diff)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>ATT_weighted_count <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">sum</span>(matched_prospensity_dataset<span class="sc">$</span>tobacco) <span class="sc">*</span> dif_in_treated</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>ATT_weighted_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -13.361</code></pre>
</div>
</div>
<p>For the treated smoker mothers, the tobacco effects on their child birth weight is lower by 13 grams on average than for its counterfactual non smoking mothers. This means that the treatment has caused lower birth weight in the treated group of mothers. For any other units of population who shares similar covariates as treated group, the birth weight of their child will be lower by 13 grams on average if they were to start smoking tobacco.</p>
</section>
<section id="ate-with-wls-matching" class="level4">
<h4 class="anchored" data-anchor-id="ate-with-wls-matching">ATE with WLS Matching</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Weighted least Squares (WLS) estimator Preparation</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>smoking_data <span class="ot">&lt;-</span> smoking_data <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weights =</span> tobacco <span class="sc">/</span> prospensity_scores <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> tobacco) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> prospensity_scores))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Weighted least Squares (WLS) Estimates</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>wls <span class="ot">&lt;-</span> <span class="fu">lm</span>(birthwgt <span class="sc">~</span> tobacco <span class="sc">+</span> mage <span class="sc">+</span>  meduc <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                           mblack <span class="sc">+</span> alcohol <span class="sc">+</span> first <span class="sc">+</span> diabete <span class="sc">+</span> anemia, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> smoking_data, <span class="at">weights =</span> weights)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = birthwgt ~ tobacco + mage + meduc + mblack + alcohol + 
    first + diabete + anemia, data = smoking_data, weights = weights)

Weighted Residuals:
   Min     1Q Median     3Q    Max 
 -7283   -374     32    396  12243 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 3122.734     11.584  269.58  &lt; 2e-16 ***
tobacco        1.426      3.241    0.44     0.66    
mage           0.219      0.358    0.61     0.54    
meduc         23.497      0.881   26.69  &lt; 2e-16 ***
mblack      -215.695      4.978  -43.33  &lt; 2e-16 ***
alcohol     -174.499     13.803  -12.64  &lt; 2e-16 ***
first        -65.326      3.509  -18.61  &lt; 2e-16 ***
diabete       72.223     12.213    5.91  3.4e-09 ***
anemia       -23.746     16.766   -1.42     0.16    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 698 on 94163 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.0369,    Adjusted R-squared:  0.0368 
F-statistic:  451 on 8 and 94163 DF,  p-value: &lt;2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Present results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The WLS matching is weighted based on propensity scores, meaning unit with higher similarity in covariates gets more weights. Based on this matching, the average birth weight of children for non smoker mother or control group is 3122.7338, keeping all other variables unchanged. This is statistically significant at 5% signficance. Of all the covariates, mblack covariates has greatest influence in outcome. i.e If the women identifies as black, the birth weight of the child is lower by 241 grams, which is significant. Besides, other covariates like drinking alcohol, first born child, and diabetes in covariates also significantly influence birthweight. However, tobacco appears insignificant at 5 percent signficance level. The model only explains 3 percent of variation given by R squared in birth weight of children. This means that the model is not a good fit for the data.</p>
</section>
<section id="differences-in-estimates" class="level4">
<h4 class="anchored" data-anchor-id="differences-in-estimates">Differences in Estimates</h4>
<p>There are certain factors that influences the output more than other covariates. This was also shown by the coefficients in Balance estimates in previous step. When using ATT with propensity score matching, the model assumed that all covariates has equal influence in determining the treatment status. But in reality, this is not always true. The WLS matching takes weights of each covariates into account, thus providing different output than ATT. if all the covariates had same weights, we would have got same estimate using both ATT and WLS matching.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="part-2-panel-model-and-fixed-effects" class="level3">
<h3 class="anchored" data-anchor-id="part-2-panel-model-and-fixed-effects">Part 2 Panel model and fixed effects</h3>
<section id="estimating-effect-with-first-difference" class="level4">
<h4 class="anchored" data-anchor-id="estimating-effect-with-first-difference">Estimating Effect with First Difference</h4>
<p>Working with new sets of data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the datasets</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>progresa_pre_1997 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"featured_projects/econometrics/data/progresa_pre_1997.csv"</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>progresa_post_1999 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"featured_projects/econometrics/data/progresa_post_1999.csv"</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Append post to pre dataset </span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>progresa <span class="ot">&lt;-</span> <span class="fu">rbind</span>(progresa_pre_1997, progresa_post_1999)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Estimate a first-difference (FD) regression manually, interpret the results briefly (size of coefficient and precision!) *Note: Calculate the difference between pre- and post- program outcomes for each family.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Code included to help get you started</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="do">## i. Sort the panel data in the order in which you want to take differences, i.e. by household and time.</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Create first differences of variables</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a> progresa_difference <span class="ot">&lt;-</span> progresa <span class="sc">%&gt;%</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">arrange</span>(hhid, year) <span class="sc">%&gt;%</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(hhid) <span class="sc">%&gt;%</span> </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="do">## ii. Calculate the first difference using the lag function from the dplyr package.</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">vani_fd =</span> vani <span class="sc">-</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(vani))</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="do">## iii. Estimate manual first-difference regression (Estimate the regression using the newly created variables)</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>first_difference_manual <span class="ot">&lt;-</span> <span class="fu">lm</span>(vani_fd <span class="sc">~</span>  treatment, </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> progresa_difference)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard errors</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>se_fdman <span class="ot">&lt;-</span> <span class="fu">coeftest</span>(first_difference_manual, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(first_difference_manual, <span class="at">type =</span> <span class="st">"HC2"</span>, <span class="at">method=</span><span class="st">"white1"</span>))[, <span class="st">"Std. Error"</span>]</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Reformat standard errors for stargazer()</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>se_fdman <span class="ot">&lt;-</span> <span class="fu">list</span>(se_fdman)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results with stargazer</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(first_difference_manual, <span class="at">keep=</span><span class="fu">c</span>(<span class="st">"treatment"</span>), <span class="at">se =</span> se_fdman, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                              vani_fd          
-----------------------------------------------
treatment                   287.900***         
                             (86.805)          
                                               
-----------------------------------------------
Observations                  13,514           
R2                             0.001           
Adjusted R2                    0.001           
Residual Std. Error   4,929.900 (df = 13512)   
F Statistic          11.312*** (df = 1; 13512) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>First Difference regression estimate tells that there is an average of 287.905 increase in animal holdings in treated households. This is statistically significant at 5% significance level, and standards errors at 86.805, which is also significant. When the estimate was calculated without calculating the first difference, the estimate had shown decreased in animal holding. This change in estimate values infers that there is unseen omitted variable that has constant effect on animal holdings which FD accounted. However, the model only explains 0.1% of all variations that is observed in animal holding, meanings there are unseen omitted variables.</p>
</section>
<section id="fixed-effects-estimates" class="level4">
<h4 class="anchored" data-anchor-id="fixed-effects-estimates">Fixed Effects Estimates</h4>
<p>Now also run a fixed effects (FE or ‘within’) regression and compare the results. Interpret the estimated treatment effects briefly (size of coefficient and precision!)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Fixed Effects Regression</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pglm)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>fixed_effects <span class="ot">&lt;-</span> plm<span class="sc">::</span><span class="fu">plm</span>(vani <span class="sc">~</span> treatment, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"state"</span>, <span class="st">"year"</span>),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">model =</span> <span class="st">"within"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">effect =</span> <span class="st">"twoways"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> progresa)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard errors (note slightly different procedure with plm package)</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>se_fixed_effect <span class="ot">&lt;-</span> <span class="fu">coeftest</span>(fixed_effects, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(fixed_effects, <span class="at">type =</span> <span class="st">"HC2"</span>, <span class="at">method=</span><span class="st">"white1"</span>))[, <span class="st">"Std. Error"</span>]</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Reformat standard errors for stargazer()</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>se_within1 <span class="ot">&lt;-</span> <span class="fu">list</span>(se_fixed_effect)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#use kable to create table of estimates and all</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fixed_effects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Twoways effects Within Model

Call:
plm::plm(formula = vani ~ treatment, data = progresa, effect = "twoways", 
    model = "within", index = c("state", "year"))

Balanced Panel: n = 7, T = 2, N = 27996

Residuals:
   Min. 1st Qu.  Median 3rd Qu.    Max. 
  -4958   -2013   -1074     151   79340 

Coefficients:
          Estimate Std. Error t-value Pr(&gt;|t|)    
treatment   -231.8       55.9   -4.15  3.4e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    5.86e+11
Residual Sum of Squares: 5.85e+11
R-Squared:      0.000614
Adj. R-Squared: 0.000329
F-statistic: 17.2057 on 1 and 27987 DF, p-value: 3.36e-05</code></pre>
</div>
</div>
<p>The Fixed Effects(FE) estimates tells that the average animal holding increased by 231.84 animals between 1997 and 1999 in treated states. This is significant at 5% confidence. However, the model explains only 0.6% variation observed in the animal holding, with standard error 56.66, which is calculated manually for grouped units in FE.</p>
<p>Unlike first difference (FD) that compares nearest units to estimate the relation, the fixed effects(FE) looks at the average across time and space. Since there are only two time periods, the average estimate from fixed effect are going to be similar to regression estimate from first difference.</p>
</section>
</section>
<section id="first-difference-and-fixed-effects-and-omitted-variable-problems" class="level2">
<h2 class="anchored" data-anchor-id="first-difference-and-fixed-effects-and-omitted-variable-problems">First Difference and Fixed Effects and Omitted Variable Problems</h2>
<p>Explain briefly how the FD and FE estimator solves a specific omitted variable problem? Look at the example on beer tax and traffic fatalities from class to start thinking about ommitted variables. Give an example of a potential omitted variable for the example we are working with here that might confound our results? For that omitted variable, is a FE or FD estimator better? One example is enough.</p>
<p>The FD and FE estimator solves the omitted variable problem by removing the constant effect of the omitted variable. It does so by subtracting the coefficients that has remained constant overtime. However, both FD and FE must satisfy Common Trends Assumptions for panel dataset, which is both treatment and control group must have similar trend for that omitted variable. If that assumptions hold, the FE and FD can remove them, and give result that is free from omitted variable bias.</p>
<p>For the example we are working with here, a potential omitted variable that might confound our results is the change in the price of animal feed. If the price of animal feed has increased over time, it might have caused the decrease in animal holdings. In this case, the FE estimator is better because it removes the constant effect of the omitted variable, which is the change in the price of animal feed, and gives us a estimate that is free from this omitted variable.</p>
<p>However, mathematically, the FD and FE both will produce same result here becuase of only two time periods(1997 and 1999). If we were to compare the units across multiple time points, lets say 2000, 2002 and more, the FE estimator would be better. Becuase, FE estimates based on average difference across time, which is more robust to the omitted variable bias than FD estimator.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Sujan-Bhattarai12">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2023, Sujan Bhattarai
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>